# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Jiyun Won
description: >- # this means to ignore newlines until "baseurl:"
  Jiyun Won
baseurl: "" # the subpath of the site
url: "https://w1jyun.github.io" # the base hostname & protocol for the site
og_image: /assets/img/profile-pic.jpg
google_analytics: "G-277RPQRMBH"

header:
  pages:
    - name: About
      slug: /
    - name: CV
      slug: /cv
    - name: Creations
      slug: /creations
footer:
  show_powered_by: false
  contact:
    - name: Email
      value: w1jyun@postech.ac.kr
      link: mailto:w1jyun@postech.ac.kr
  follow:
    - name: LinkedIn
      link: http://linkedin.com/in/jiyunwon
    - name: GitHub
      link: http://github.com/w1jyun

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
